<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [ ]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

In [5]:
%%sql

SELECT table_name
FROM information_schema.tables
WHERE table_schema='public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [9]:
%%sql

SELECT *
FROM information_schema.columns
WHERE table_name = 'customer';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,public,customer,customerkey,1,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,public,customer,geoareakey,2,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,contoso_100k,public,customer,startdt,3,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,contoso_100k,public,customer,enddt,4,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,public,customer,birthday,18,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
5,contoso_100k,public,customer,age,19,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
6,contoso_100k,public,customer,latitude,23,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
7,contoso_100k,public,customer,longitude,24,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
8,contoso_100k,public,customer,middleinitial,9,None,YES,character varying,5.00,20.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
9,contoso_100k,public,customer,surname,10,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
10,contoso_100k,public,customer,streetaddress,11,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
11,contoso_100k,public,customer,city,12,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
12,contoso_100k,public,customer,state,13,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
13,contoso_100k,public,customer,statefull,14,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
14,contoso_100k,public,customer,zipcode,15,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
15,contoso_100k,public,customer,country,16,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
16,contoso_100k,public,customer,countryfull,17,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
17,contoso_100k,public,customer,company,21,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
18,contoso_100k,public,customer,vehicle,22,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
19,contoso_100k,public,customer,occupation,20,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
20,contoso_100k,public,customer,continent,5,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
21,contoso_100k,public,customer,gender,6,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
22,contoso_100k,public,customer,title,7,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
23,contoso_100k,public,customer,givenname,8,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES

Calculate Net Revenue

In [20]:
%%sql

SELECT
  orderdate,
  quantity * netprice * exchangerate AS net_revenue
FROM sales
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2015-01-01        63.49
1  2015-01-01       423.28
2  2015-01-01       108.75
3  2015-01-01      1146.75
4  2015-01-01       950.25
5  2015-01-01      1302.91
6  2015-01-01        58.73
7  2015-01-01       224.98
8  2015-01-01       263.11
9  2015-01-01       578.52

Recent Sales >= 2020

In [21]:
%%sql

SELECT
  orderdate,
  quantity * netprice * exchangerate AS net_revenue
FROM sales
WHERE orderdate::date >= '2020-01-01'
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2020-01-01        99.47
1  2020-01-01       139.97
2  2020-01-01       669.39
3  2020-01-01      4090.60
4  2020-01-01       237.15
5  2020-01-01      1507.16
6  2020-01-01       189.35
7  2020-01-01       539.90
8  2020-01-01      5590.00
9  2020-01-01      3580.00

Add customer info

In [23]:
%%sql

SELECT
  s.orderdate,
  s.quantity * s.netprice * s.exchangerate AS net_revenue,
  c.*
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE orderdate::date >= '2020-01-01'
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,2020-01-01,99.47,593517,31,1985-04-08,2029-05-17,Europe,female,Ms.,Heike,...,46499,DE,Germany,1986-10-27,34,Measurer,Star Interior Design,2007 Toyota Aygo,51.79,6.60
1,2020-01-01,139.97,593517,31,1985-04-08,2029-05-17,Europe,female,Ms.,Heike,...,46499,DE,Germany,1986-10-27,34,Measurer,Star Interior Design,2007 Toyota Aygo,51.79,6.60
2,2020-01-01,669.39,593517,31,1985-04-08,2029-05-17,Europe,female,Ms.,Heike,...,46499,DE,Germany,1986-10-27,34,Measurer,Star Interior Design,2007 Toyota Aygo,51.79,6.60
3,2020-01-01,4090.60,593517,31,1985-04-08,2029-05-17,Europe,female,Ms.,Heike,...,46499,DE,Germany,1986-10-27,34,Measurer,Star Interior Design,2007 Toyota Aygo,51.79,6.60
4,2020-01-01,237.15,307502,10,1984-08-03,2020-02-17,North America,female,Mrs.,Michelle,...,V2P 2M1,CA,Canada,1976-09-27,44,Employment assistant,Handy Andy,2003 Citroen C8,49.22,-122.05
5,2020-01-01,1507.16,1413265,591,1997-06-27,2027-10-13,North America,male,Mr.,Jason,...,39201,US,United States,1942-12-23,78,Occupational social worker,Monk Home Funding Services,1995 Peugeot 504,32.39,-90.13
6,2020-01-01,189.35,1413265,591,1997-06-27,2027-10-13,North America,male,Mr.,Jason,...,39201,US,United States,1942-12-23,78,Occupational social worker,Monk Home Funding Services,1995 Peugeot 504,32.39,-90.13
7,2020-01-01,539.90,1413265,591,1997-06-27,2027-10-13,North America,male,Mr.,Jason,...,39201,US,United States,1942-12-23,78,Occupational social worker,Monk Home Funding Services,1995 Peugeot 504,32.39,-90.13
8,2020-01-01,5590.00,1567083,613,1994-09-15,2021-12-25,North America,male,Mr.,James,...,99012,US,United States,1987-03-24,33,Industrial-organizational psychologist,Standard Brands Paint Company,2007 Isuzu I-350,47.46,-117.19
9,2020-01-01,3580.00,1855428,609,1992-11-15,2023-09-03,North America,male,Mr.,Johnny,...,78229,US,United States,1945-10-03,75,Public address system announcer,Disc Jockey,2003 Chevrolet Monte Carlo,29.45,-98.55